#!/bin/sh
# postrm script for udpscope

set -e

case "$1" in
    purge|remove|upgrade)
        ;;
        
    abort-install|abort-upgrade)
        ;;
        
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0